class Constants {
    static TYPE_OTP_LOGIN = "LOGIN";
    static X_ACCESS_TOKEN = "x-access-token";
    
    static ON_OFF_SETTING_SENT_MAIL_OTP = true;
    static ON_OFF_SETTING_LOG_ENABLE = true;
    static ON_OFF_SETTING_LOG_OTP = true;
    
    static INVALID_PROTOBUF = "INVALID_PROTOBUF";
    static DATA_MISSING = "DATA_MISSING";
    static DATA_NOT_DECRYPT = "DATA_NOT_DECRYPT";
    static EMAIL_MISSING = "EMAIL_MISSING";
    static EMAIL_NOT_FORMAT = "EMAIL_NOT_FORMAT";
    static EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS";
    static OTP_SEND_FAIL = "OTP_SEND_FAIL";
    static SERVER_ERROR = "SERVER_ERROR";
    static OTP_NOT_VERIFIED = "OTP_NOT_VERIFIED";
    static EMAIL_DOSE_NOT_EXISTS = "EMAIL_DOSE_NOT_EXISTS";
    static ACCOUNT_LOCKED = "ACCOUNT_LOCKED";
    static OTP_LIMIT = "OTP_LIMIT";
    static PASSWORD_NOT_SET = "PASSWORD_NOT_SET";
    static LOGIN_ERROR = "LOGIN_ERROR";
    static TOKEN_MISSING = "TOKEN_MISSING";
    static INVALID_EXPIRATION = "INVALID_EXPIRATION";
    static INVALID_TOKEN = "INVALID_TOKEN";
    static OTP_EXPIRED = "OTP_EXPIRED";
    static OTP_NOT_VALID = "OTP_NOT_VALID";

    static USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
    static UPDATE_SUCCESS = "UPDATE_SUCCESS";
    static ACCOUNT_CAN_LOGIN = "ACCOUNT_CAN_LOGIN";
    static ACCOUNT_CAN_NOT_LOGIN = "ACCOUNT_CAN_NOT_LOGIN";
    static LOGIN_SUCCESS = "LOGIN_SUCCESS";
    static OTP_CONFIRMED = "OTP_CONFIRMED";
    static SETPASS_SUCCESS = "SETPASS_SUCCESS";
    static OTP_RECENT_SUCCESS = "OTP_RECENT_SUCCESS";
    static LOGOUT_SUCCESS = "LOGOUT_SUCCESS";


  }
  
  module.exports = Constants;
  